services:
  evauctiontrader.presentation:
    build:
      context: .
      dockerfile: EVAuctionTrader.Presentation/Dockerfile
    image: evauctiontrader-presentation:latest
    depends_on:
      - evauctiontrader.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Host=evauctiontrader.database;Port=5432;Database=EVAuctionTraderDb;Username=postgres;Password=postgres;Pooling=true"
      - "JWT__SecretKey=EVDealerSales_SECRETKEY_SIEUCAPBAOMAT_VAYMACHUADU16KYTU"
      - "JWT__Issuer=EVAuctionTrader_Issuer"
      - "JWT__Audience=EVAuctionTrader_Audience"
    ports:
      - "5000:5000"
    volumes:
      - ./data/keys:/keys

  evauctiontrader.database:
    image: postgres:15
    container_name: evauctiontrader-postgres
    environment:
      - POSTGRES_DB=EVAuctionTraderDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
   driver: local
