services:
  evauctiontrader.presentation:
    build:
      context: .
      dockerfile: EVAuctionTrader.Presentation/Dockerfile
    image: evauctiontrader-presentation:latest
    depends_on:
      - evauctiontrader.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=evauctiontrader.database,1433;Database=EVAuctionTraderDb;User Id=sa;Password=StrongPassw0rd123;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
      - "JWT__SecretKey=EVDealerSales_SECRETKEY_SIEUCAPBAOMAT_VAYMACHUADU16KYTU"
      - "JWT__Issuer=EVAuctionTrader_Issuer"
      - "JWT__Audience=EVAuctionTrader_Audience"
    ports:
      - "5000:5000"
    volumes:
      - ./data/keys:/keys

  evauctiontrader.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: evauctiontrader-sqlserver
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassw0rd123
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
   driver: local
